#!/usr/bin/env python3
"""MCP server for ahk-lint — agents can self-check generated AHK code."""

import json
import os
import sys
from pathlib import Path
from typing import Optional

from ahk_lint import Linter, LinterConfig, load_grammar

try:
    from fastmcp import FastMCP, Context
except ImportError:
    print("fastmcp not installed. Install with: pip install fastmcp", file=sys.stderr)
    sys.exit(1)


def create_linter() -> tuple:
    """Create shared linter instance."""
    grammar = load_grammar()
    config = LinterConfig.load()
    linter = Linter(config, grammar)
    return linter


mcp = FastMCP("ahk-lint", version="2.0.0")


@mcp.tool(annotations={"readOnlyHint": True})
async def lint_ahk_script(source: str, ctx: Optional[Context] = None) -> dict:
    """Lint an AutoHotkey v2 script and return diagnostics.

    Use this before executing any AHK script generated by an LLM.
    Catches v1 syntax patterns, safety issues, style problems, and dead code.

    Args:
        source: The complete AHK source code to lint.
    Returns:
        A dict with issues list, total count, and severity breakdown.
    """
    linter = create_linter()
    # Write to temp file for linting
    import tempfile
    with tempfile.NamedTemporaryFile(mode="w", suffix=".ahk", delete=False, encoding="utf-8") as f:
        f.write(source)
        tmp_path = f.name

    try:
        issues = linter.lint_file(Path(tmp_path))
        by_severity = {"error": 0, "warning": 0, "suggestion": 0}
        for issue in issues:
            by_severity[issue.get("severity", "warning")] = by_severity.get(issue.get("severity", "warning"), 0) + 1
        return {
            "issues": issues,
            "total": len(issues),
            "by_severity": by_severity,
            "clean": len(issues) == 0,
        }
    finally:
        os.unlink(tmp_path)


@mcp.tool(annotations={"readOnlyHint": True})
async def lint_ahk_file(path: str, ctx: Optional[Context] = None) -> dict:
    """Lint an AHK file on disk.

    Args:
        path: Absolute path to the .ahk file.
    Returns:
        A dict with issues list, total count, and severity breakdown.
    """
    linter = create_linter()
    file_path = Path(path)
    if not file_path.exists():
        return {"error": f"File not found: {path}", "issues": [], "total": 0, "clean": True}
    issues = linter.lint_file(file_path)
    by_severity = {"error": 0, "warning": 0, "suggestion": 0}
    for issue in issues:
        by_severity[issue.get("severity", "warning")] = by_severity.get(issue.get("severity", "warning"), 0) + 1
    return {
        "issues": issues,
        "total": len(issues),
        "by_severity": by_severity,
        "clean": len(issues) == 0,
    }


@mcp.tool()
async def fix_ahk_script(source: str, ctx: Optional[Context] = None) -> dict:
    """Auto-fix common v1→v2 issues in an AHK script.

    Applies mechanical fixes: Random, StringSplit, IfEqual, FileRead,
    FormatTime, %var% deref, Menu/Tray, etc.

    Args:
        source: The complete AHK source code to fix.
    Returns:
        A dict with the fixed source, whether changes were made, and what was fixed.
    """
    linter = create_linter()
    import tempfile
    with tempfile.NamedTemporaryFile(mode="w", suffix=".ahk", delete=False, encoding="utf-8") as f:
        f.write(source)
        tmp_path = f.name

    try:
        fixed, new_content = linter.fix_file(Path(tmp_path))
        return {
            "fixed": fixed,
            "source": new_content if fixed else source,
            "message": "Script was auto-fixed." if fixed else "No fixes needed.",
        }
    finally:
        os.unlink(tmp_path)


@mcp.tool(annotations={"readOnlyHint": True})
async def lint_check(source: str, ctx: Optional[Context] = None) -> dict:
    """Quick check: is this AHK script clean (no errors)?

    Use this as a pre-flight check before executing LLM-generated AHK code.
    Returns just a pass/fail boolean for quick decisions.

    Args:
        source: The complete AHK source code to check.
    Returns:
        A dict with clean (bool), errors count, and first error message.
    """
    result = await lint_ahk_script(source, ctx)
    if result.get("error"):
        return {"clean": False, "errors": 1, "first_error": result["error"]}
    errors = result.get("by_severity", {}).get("error", 0)
    first = ""
    if errors > 0:
        for issue in result.get("issues", []):
            if issue.get("severity") == "error":
                first = f"L{issue['line']}: {issue['message']}"
                break
    return {"clean": errors == 0, "errors": errors, "first_error": first}


@mcp.tool(annotations={"readOnlyHint": True})
async def list_checks(ctx: Optional[Context] = None) -> dict:
    """List all available lint checks with their IDs, severity, and descriptions."""
    from checks.v1_syntax import V1SyntaxCheck
    from checks.safety import SafetyCheck
    from checks.style import StyleCheck
    from checks.dead_code import DeadCodeCheck
    from checks.command_rules import CommandRulesCheck
    from checks.function_renames import FunctionRenamesCheck, OldObjectModelCheck

    config = LinterConfig.load()
    all_checks = [
        ("V1 Syntax", V1SyntaxCheck(config), [
            ("W001", "Random, var → var := Random()", "error"),
            ("W002", "StringSplit → StrSplit()", "error"),
            ("W003", "Gui, Add → gui.Add()", "error"),
            ("W004", "IfEqual → if ( = )", "error"),
            ("W005", "FileRead, var → var := FileRead()", "error"),
            ("W006", "FormatTime, var → var := FormatTime()", "error"),
            ("W007", "Gosub → function call", "warning"),
            ("W008", "%var% → var", "error"),
            ("W009", "Menu, Tray → A_TrayMenu", "error"),
            ("W010", "SetTimer, Label → SetTimer(Func)", "warning"),
        ]),
        ("Command Rules", CommandRulesCheck(config), [
            ("V1_Win*", "Window commands (WinActivate, WinMove, etc.)", "error"),
            ("V1_Control*", "Control commands (ControlClick, etc.)", "error"),
            ("V1_File*", "File commands (FileCopy, FileRead, etc.)", "error"),
            ("V1_Send*", "Send/Input commands", "error"),
            ("V1_String*", "String commands (StringLeft → SubStr)", "error"),
            ("V1_Reg*", "Registry commands", "error"),
            ("V1_Env*", "Env commands", "error"),
        ]),
        ("Function Renames", FunctionRenamesCheck(config), [
            ("V1_FUNC_*", "Renamed functions (LV_Add → ListView.Add, Asc → Ord)", "error"),
        ]),
        ("Old Object Model", OldObjectModelCheck(config), [
            ("V1_PSEUDO_ARRAY", "Pseudo-arrays (Array%i%)", "error"),
            ("V1_HASKEY", "HasKey → Has", "error"),
        ]),
        ("Safety", SafetyCheck(config), [
            ("S003", "I/O without try/catch", "error"),
            ("S005", "Missing #Requires/#SingleInstance", "warning"),
        ]),
        ("Style", StyleCheck(config), [
            ("S010", "Tab characters", "suggestion"),
            ("S011", "Trailing whitespace", "suggestion"),
            ("S012", "Line too long", "suggestion"),
        ]),
        ("Dead Code", DeadCodeCheck(config), [
            ("S020", "Unused variable", "warning"),
            ("S021", "Unreachable code", "warning"),
        ]),
    ]
    result = []
    for cat_name, _, rules in all_checks:
        for rule_id, desc, severity in rules:
            result.append({"id": rule_id, "description": desc, "severity": severity, "category": cat_name})
    return {"rules": result, "total": len(result)}


if __name__ == "__main__":
    mcp.run(transport="stdio")
